language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install behave colormath coverage multipledispatch numpy>=1.7
script:
  - coverage run --source toyplot -m nose
  - coverage run --source toyplot --append -m behave
  - coverage report
