language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-gtk2
install:
  - pip install behave colormath coverage coveralls multipledispatch networkx numpy>=1.7
script:
  - coverage run --source toyplot --omit toyplot/testing.py -m nose
  - coverage run --source toyplot --omit toyplot/testing.py -m behave --append
  - coverage report
after_script:
  - coveralls
