sudo: false
language: python
python:
    - "2.7"
    - "3.3"
addons:
    apt:
        packages:
        - ghostscript
install:
    - env | sort
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION graphviz mock multipledispatch networkx numpy=1.8.2 pandas=0.14.1 pillow pip pylint reportlab
    - source activate test-environment
    - pip install arrow behave "colormath>=2.1.0" coverage coveralls nose-exclude pypng
    - wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
    - mkdir ffmpeg
    - tar xf ffmpeg-release-64bit-static.tar.xz --strip-components 1 -C ffmpeg
    - export PATH=$TRAVIS_BUILD_DIR/ffmpeg:$PATH
script:
    - coverage run --source toyplot --omit toyplot/testing.py,toyplot/qt/*.py -m nose --exclude-dir toyplot
    - coverage run --append --source toyplot --omit toyplot/testing.py,toyplot/qt/*.py -m behave
    - coverage report
    - python backend-report.py
after_script:
    - coveralls
